# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Staypoint < Formula
  desc "Autonomous AI Agent Ops, Quota Pacing & Cross-AI Context Platform"
  homepage "https://github.com/VinnyVanGogh/staypoint"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/VinnyVanGogh/staypoint/releases/download/v0.3.0/staypoint_0.3.0_darwin_amd64.tar.gz"
      sha256 "fb6095d53e94275440e70b4733a38f6eea9a86c4518bc8a9f205808654836646"

      define_method(:install) do
        bin.install "staypoint"
        bin.install "staypointd" if File.exist?("staypointd")
        bin.install_symlink "staypoint" => "mesh"
        bin.install_symlink "staypointd" => "meshd" if (bin/"staypointd").exist?
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/VinnyVanGogh/staypoint/releases/download/v0.3.0/staypoint_0.3.0_darwin_arm64.tar.gz"
      sha256 "f8c1e20be4ed5738b3c6d8cf2745a3203824c7db1e8f5cd26fd63c860ae0fce5"

      define_method(:install) do
        bin.install "staypoint"
        bin.install "staypointd" if File.exist?("staypointd")
        bin.install_symlink "staypoint" => "mesh"
        bin.install_symlink "staypointd" => "meshd" if (bin/"staypointd").exist?
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/VinnyVanGogh/staypoint/releases/download/v0.3.0/staypoint_0.3.0_linux_amd64.tar.gz"
      sha256 "ab5539fff33debb6e173bf22961958207772942c1b3e143eb6f23be93bb8f0ec"
      define_method(:install) do
        bin.install "staypoint"
        bin.install "staypointd" if File.exist?("staypointd")
        bin.install_symlink "staypoint" => "mesh"
        bin.install_symlink "staypointd" => "meshd" if (bin/"staypointd").exist?
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/VinnyVanGogh/staypoint/releases/download/v0.3.0/staypoint_0.3.0_linux_arm64.tar.gz"
      sha256 "397077a5d90ecec0e51308863cd2b9b010eab0573b1c8094396b5c4dae6b546f"
      define_method(:install) do
        bin.install "staypoint"
        bin.install "staypointd" if File.exist?("staypointd")
        bin.install_symlink "staypoint" => "mesh"
        bin.install_symlink "staypointd" => "meshd" if (bin/"staypointd").exist?
      end
    end
  end

  def caveats
    <<~EOS
      StayPoint installed! Add shell integration to ~/.zshrc:
        eval "$(staypoint init --shell)"
      Start background daemon:
        staypoint init
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/staypoint version")
  end
end
