# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Staypoint < Formula
  desc "Autonomous AI Agent Ops, Quota Pacing & Cross-AI Context Platform"
  homepage "https://github.com/VinnyVanGogh/staypoint"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/VinnyVanGogh/staypoint/releases/download/v0.2.0/staypoint_0.2.0_darwin_amd64.tar.gz"
      sha256 "8a4bfbe6f163dcb42d1bc58a0a39b4d4f8d8e5fb47395886d2a60e10b7757cc6"

      define_method(:install) do
        bin.install "staypoint"
        bin.install "staypointd" if File.exist?("staypointd")
        bin.install_symlink "staypoint" => "mesh"
        bin.install_symlink "staypointd" => "meshd" if (bin/"staypointd").exist?
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/VinnyVanGogh/staypoint/releases/download/v0.2.0/staypoint_0.2.0_darwin_arm64.tar.gz"
      sha256 "c468c7c5c4c25ae05309834b54bdeb8cef4fc70627ede904d37b6c63f45844a8"

      define_method(:install) do
        bin.install "staypoint"
        bin.install "staypointd" if File.exist?("staypointd")
        bin.install_symlink "staypoint" => "mesh"
        bin.install_symlink "staypointd" => "meshd" if (bin/"staypointd").exist?
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/VinnyVanGogh/staypoint/releases/download/v0.2.0/staypoint_0.2.0_linux_amd64.tar.gz"
      sha256 "b7c28306c105c9d78320fed3b737969e2c2968d1ae23cf258c638090171d42ed"
      define_method(:install) do
        bin.install "staypoint"
        bin.install "staypointd" if File.exist?("staypointd")
        bin.install_symlink "staypoint" => "mesh"
        bin.install_symlink "staypointd" => "meshd" if (bin/"staypointd").exist?
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/VinnyVanGogh/staypoint/releases/download/v0.2.0/staypoint_0.2.0_linux_arm64.tar.gz"
      sha256 "413815e646571115fcc5fb06943e28de6e0e43fdc125d1e289f172db81004591"
      define_method(:install) do
        bin.install "staypoint"
        bin.install "staypointd" if File.exist?("staypointd")
        bin.install_symlink "staypoint" => "mesh"
        bin.install_symlink "staypointd" => "meshd" if (bin/"staypointd").exist?
      end
    end
  end

  def caveats
    <<~EOS
      StayPoint installed! Add shell integration to ~/.zshrc:
        eval "$(staypoint init --shell)"
      Start background daemon:
        staypoint init
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/staypoint version")
  end
end
